version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn clean install
      - mvn test
      - mvn sonar:sonar
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
      
      
      

  
